artifacts_config:
  artifacts_dir: artifacts

data_ingestion_config:
  dataset_download_url: https://github.com/YogitaPatil5/dsai_data/raw/refs/heads/main/books_data.zip 
  dataset_dir: dataset
  ingested_dir: ingested_data
  raw_data_dir: raw_data

data_validation_config:
  clean_data_dir: clean_data
  serialized_objects_dir: serialized_objects
  books_csv_file: BX-Books.csv
  ratings_csv_file: BX-Book-Ratings.csv
  final_rating_file_name: final_rating.pkl
  book_pivot_table_file_name: book_pivot.pkl
  book_names_file_name: book_names.pkl


data_transformation_config:
  transformed_data_dir: transformed_data
  transformed_data_file_name: transformed_data.pkl



model_trainer_config:
  trained_model_dir: trained_model
  trained_model_name: model.pkl
  model_algorithm: brute


